# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.4
  - 0.5
notifications:
  email: false
sudo: required
dist: trusty
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd())'
  - wget http://scip.zib.de/download/release/scipoptsuite-3.2.1.tgz
  - tar xzf scipoptsuite-3.2.1.tgz
  - cd scipoptsuite-3.2.1/
  - rm Makefile.doit
  - wget http://scip.zib.de/download/bugfixes/scip-3.2.1/Makefile.doit
  - make SHARED=true GMP=false READLINE=false ZLIB=false scipoptlib
  - cd ..
  - wget https://github.com/SCIP-Interfaces/CSIP/archive/v0.3.0.zip
  - unzip master.zip
  - cd CSIP-master
  - mkdir lib
  - ln -s `readlink -f ../scipoptsuite-3.2.1/scip-3.2.1/src` lib/include
  - ln -s `readlink -f ../scipoptsuite-3.2.1/lib/libscipopt.so` lib/libscipopt.so
  - make test
  - export CSIP_HOME=`pwd`
  - cd ..
  - julia -e 'Pkg.build("SCIP"); Pkg.test("SCIP"; coverage=true)'
